# Cloud Build configuration for Frontend
# Triggered on push to main branch
# Builds Docker image and deploys to Cloud Run

steps:
  # Step 1: Get Backend URL from Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'get-backend-url'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Getting backend URL from Cloud Run..."
        BACKEND_URL=$$(gcloud run services describe devfest-backend --region=africa-south1 --format='value(status.url)' 2>/dev/null || echo "https://backend-not-deployed-yet")
        echo "$$BACKEND_URL" > /workspace/backend_url.txt
        echo "Backend URL: $$BACKEND_URL"

  # Step 2: Build the Docker image with backend URL
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BACKEND_URL=$$(cat /workspace/backend_url.txt)
        echo "Building frontend with API URL: $$BACKEND_URL"
        
        docker build \
          -t gcr.io/$$PROJECT_ID/devfest-frontend:$$SHORT_SHA \
          -t gcr.io/$$PROJECT_ID/devfest-frontend:latest \
          -f docker/Dockerfile.frontend \
          --build-arg REACT_APP_API_URL=$$BACKEND_URL \
          .

  # Step 3: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend-sha'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/devfest-frontend:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend-latest'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/devfest-frontend:latest'

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-frontend-to-cloud-run'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BACKEND_URL=$$(cat /workspace/backend_url.txt)
        echo "Deploying frontend to Cloud Run..."
        echo "Configured to use Backend URL: $$BACKEND_URL"
        
        gcloud run deploy devfest-frontend \
          --image=gcr.io/$$PROJECT_ID/devfest-frontend:$$SHORT_SHA \
          --platform=managed \
          --region=africa-south1 \
          --allow-unauthenticated \
          --port=80 \
          --memory=256Mi \
          --cpu=1 \
          --min-instances=0 \
          --max-instances=10 \
          --set-env-vars="REACT_APP_API_URL=$$BACKEND_URL"
        
        echo "Frontend deployment complete!"

  # Step 5: Get and display frontend URL
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'display-frontend-url'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        FRONTEND_URL=$$(gcloud run services describe devfest-frontend --region=africa-south1 --format='value(status.url)')
        BACKEND_URL=$$(cat /workspace/backend_url.txt)
        
        echo "=========================================="
        echo "Frontend deployed successfully!"
        echo "=========================================="
        echo "Frontend URL: $$FRONTEND_URL"
        echo "Backend URL:  $$BACKEND_URL"
        echo ""
        echo "Open the frontend URL in your browser to test!"
        echo "=========================================="

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/devfest-frontend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/devfest-frontend:latest'

# Build timeout
timeout: '1200s'

# Options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

