# Cloud Build configuration for Database Migrations
# Triggered on push to main branch (after code changes)
# Runs database migration scripts against CloudSQL

steps:
  # Step 1: Get CloudSQL Public IP
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'get-db-ip'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Getting CloudSQL public IP address..."
        DB_IP=$$(gcloud sql instances describe devfest-db-instance --format='value(ipAddresses[0].ipAddress)')
        echo "$$DB_IP" > /workspace/db_ip.txt
        echo "Database IP: $$DB_IP"
        
        # Also get connection name for reference
        INSTANCE_CONNECTION=$$(gcloud sql instances describe devfest-db-instance --format='value(connectionName)')
        echo "$$INSTANCE_CONNECTION" > /workspace/instance_connection.txt
        echo "Connection name: $$INSTANCE_CONNECTION"

  # Step 2: Run migrations using psql
  - name: 'postgres:15-alpine'
    id: 'run-migrations'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Running database migrations..."
        echo "Connecting to database: ${_DATABASE_NAME}"
        
        # Get the database IP
        DB_IP=$$(cat /workspace/db_ip.txt)
        echo "Connecting to: $$DB_IP:5432"
        
        # Wait a moment for networking
        sleep 3
        
        # Run migration files in order
        for migration_file in database/migrations/*.sql; do
          echo "Applying migration: $$migration_file"
          PGPASSWORD="${_DB_PASSWORD}" psql \
            -h $$DB_IP \
            -p 5432 \
            -U ${_DB_USER} \
            -d ${_DATABASE_NAME} \
            -f "$$migration_file" \
            -v ON_ERROR_STOP=1
          
          if [ $$? -eq 0 ]; then
            echo "✓ Migration $$migration_file applied successfully"
          else
            echo "✗ Migration $$migration_file failed"
            exit 1
          fi
        done
        
        echo "=========================================="
        echo "All migrations completed successfully!"
        echo "=========================================="

  # Step 3: Verify migrations
  - name: 'postgres:15-alpine'
    id: 'verify-migrations'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Verifying database tables..."
        
        DB_IP=$$(cat /workspace/db_ip.txt)
        
        PGPASSWORD="${_DB_PASSWORD}" psql \
          -h $$DB_IP \
          -p 5432 \
          -U ${_DB_USER} \
          -d ${_DATABASE_NAME} \
          -c "\dt" \
          -c "SELECT COUNT(*) as hello_world_count FROM hello_world;" \
          -c "SELECT COUNT(*) as applications_count FROM applications;"
        
        echo "✓ Database verification complete!"

# Substitutions - Override these in Cloud Build Trigger
substitutions:
  _DATABASE_NAME: 'devfest_db'
  _DB_USER: 'devfest_user'
  _DB_PASSWORD: 'DevF3st123-pluto-is-plan3t'

# Build timeout
timeout: '600s'

# Options
options:
  logging: CLOUD_LOGGING_ONLY

