# Cloud Build configuration for CloudSQL Database Setup
# This is a ONE-TIME setup to create the CloudSQL instance
# Run manually: gcloud builds submit --config=cloudbuild-db-setup.yaml
# Or set up as a Cloud Build trigger (manual execution only)

steps:
  # Step 1: Create CloudSQL PostgreSQL instance
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'create-cloudsql-instance'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Creating CloudSQL PostgreSQL instance..."
        echo "This may take 5-10 minutes..."
        
        gcloud sql instances create devfest-db-instance \
          --database-version=POSTGRES_15 \
          --tier=db-f1-micro \
          --region=africa-south1 \
          --storage-type=SSD \
          --storage-size=10GB \
          --backup-start-time=03:00 \
          --availability-type=zonal \
          --assign-ip \
          --authorized-networks=0.0.0.0/0 \
          --root-password="${_DB_PASSWORD}" \
          2>&1 || {
            echo ""
            echo "Instance creation failed or already exists"
            echo "Checking if instance exists..."
            if gcloud sql instances describe devfest-db-instance --format='value(name)' 2>/dev/null; then
              echo "✓ Instance already exists, continuing..."
              exit 0
            else
              echo "✗ Instance does not exist and creation failed"
              exit 1
            fi
          }
        
        echo "✓ Instance created successfully!"
    timeout: '900s'

  # Step 2: Wait for instance to be ready
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'wait-for-instance'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Waiting for CloudSQL instance to be ready..."
        for i in {1..30}; do
          STATE=$$(gcloud sql instances describe devfest-db-instance --format='value(state)' 2>/dev/null || echo "UNKNOWN")
          echo "Attempt $$i/30 - Instance state: $$STATE"
          if [ "$$STATE" = "RUNNABLE" ]; then
            echo "✓ Instance is ready!"
            exit 0
          fi
          echo "Waiting 20 seconds..."
          sleep 20
        done
        echo "✗ Instance not ready after 10 minutes"
        exit 1
    timeout: '900s'

  # Step 3: Create the database
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'create-database'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Creating database: ${_DATABASE_NAME}..."
        gcloud sql databases create ${_DATABASE_NAME} \
          --instance=devfest-db-instance \
          2>&1 || {
            if gcloud sql databases describe ${_DATABASE_NAME} --instance=devfest-db-instance 2>/dev/null; then
              echo "✓ Database already exists, continuing..."
            else
              echo "✗ Database creation failed"
              exit 1
            fi
          }
    timeout: '300s'

  # Step 4: Create database user
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'create-user'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Creating database user: ${_DB_USER}..."
        gcloud sql users create ${_DB_USER} \
          --instance=devfest-db-instance \
          --password="${_DB_PASSWORD}" \
          2>&1 || {
            if gcloud sql users list --instance=devfest-db-instance --filter="name:${_DB_USER}" --format='value(name)' 2>/dev/null | grep -q "${_DB_USER}"; then
              echo "✓ User already exists, continuing..."
            else
              echo "✗ User creation failed"
              exit 1
            fi
          }
    timeout: '300s'

  # Step 5: Display connection information
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'display-info'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=========================================="
        echo "CloudSQL Instance Setup Complete!"
        echo "=========================================="
        echo "Instance Name: devfest-db-instance"
        echo "Database: ${_DATABASE_NAME}"
        echo "User: ${_DB_USER}"
        echo "Region: africa-south1"
        echo ""
        INSTANCE_CONNECTION=$$(gcloud sql instances describe devfest-db-instance --format='value(connectionName)' 2>/dev/null || echo "ERROR")
        if [ "$$INSTANCE_CONNECTION" != "ERROR" ]; then
          echo "Connection String for Cloud Run:"
          echo "INSTANCE_CONNECTION_NAME: $$INSTANCE_CONNECTION"
          echo ""
          echo "✓ Use this in your Cloud Run services!"
        else
          echo "✗ Could not retrieve connection string"
        fi
        echo "=========================================="

# Substitutions - Override these in Cloud Build Trigger
substitutions:
  _DATABASE_NAME: 'devfest_db'
  _DB_USER: 'devfest_user'
  _DB_PASSWORD: 'DevF3st123-pluto-is-plan3t'

# Build timeout
timeout: '1800s'

# Options
options:
  logging: CLOUD_LOGGING_ONLY

